[2020-03-05 11:49:37 +0800] [2414] [INFO] Starting gunicorn 20.0.4
[2020-03-05 11:49:37 +0800] [2414] [INFO] Listening at: http://0.0.0.0:5001 (2414)
[2020-03-05 11:49:37 +0800] [2414] [INFO] Using worker: sync
[2020-03-05 11:49:37 +0800] [2417] [INFO] Booting worker with pid: 2417
2020-03-05 11:49:38.713598: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-05 11:49:38.713667: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-05 11:49:38.713678: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[2020-03-05 13:59:59 +0800] [2414] [INFO] Handling signal: hup
[2020-03-05 13:59:59 +0800] [2414] [INFO] Hang up: Master
[2020-03-05 13:59:59 +0800] [2833] [INFO] Booting worker with pid: 2833
2020-03-05 14:00:00.729583: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-05 14:00:00.729657: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-05 14:00:00.729668: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/data/doctor_online/bert_server/start.sh: line 2:  2414 Killed                  gunicorn -w 1 -b 0.0.0.0:5001 app:app
Using cache found in /root/.cache/torch/hub/huggingface_pytorch-transformers_master
Using cache found in /root/.cache/torch/hub/huggingface_pytorch-transformers_master
[2020-05-21 18:02:01 +0800] [2833] [INFO] Parent changed, shutting down: <Worker 2833>
[2020-05-21 18:02:01 +0800] [2833] [INFO] Worker exiting (pid: 2833)
tensor([[[ 1.0210,  0.0659, -0.3472,  ...,  0.5131, -0.7699,  0.0202],
         [-0.1966,  0.2660,  0.3689,  ..., -0.0650, -0.2853, -0.1777],
         [ 0.9295, -0.3890, -0.1026,  ...,  1.3917,  0.4692, -0.0851],
         ...,
         [ 1.4777,  0.7781, -0.4310,  ...,  0.7403,  0.2006, -0.1198],
         [ 0.3867, -0.2031, -0.0721,  ...,  1.0050, -0.2479, -0.3525],
         [ 0.0599,  0.2883, -0.4011,  ..., -0.1875, -0.2546,  0.0453]]])
torch.Size([1, 20, 768])
tensor([[0.0000, 0.2915]], grad_fn=<ReluBackward0>)
